version: '3.8'

services:
  backend:
    build: ../back-end  # Certifique-se de que esse caminho está correto em relação ao arquivo docker-compose.yml
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=global_solution_db
    depends_on:
      - db

  frontend:
    build: ../front-end  # Certifique-se de que esse caminho está correto em relação ao arquivo docker-compose.yml
    ports:
      - "8080:80"
    depends_on:
      - backend

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: global_solution_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
